server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" # Allow React Frontend
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: crm-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**, /api/admin/**, /api/csr/**, /api/customer/**
          filters:
            - AuthenticationFilter

        - id: oms-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/oms/**
          filters:
            - AuthenticationFilter

        - id: payment-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/payment/**, /wallet/**
          filters:
            - AuthenticationFilter

        - id: inventory-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/inventory/**
          filters:
            - AuthenticationFilter

# Security Configuration
jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG

# Distributed Tracing (Zipkin)
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
